name: 书旗
on:
  workflow_dispatch:
  schedule:
    - cron: '27 1,4 * * *'
jobs:
  build:
    runs-on: macos-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/caixukun112/js.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
         
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      - name: '【书旗小说】'
        run: |
            
          node Task/sq1.js
        
     
